import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {cookies} from "next/headers";
import Nav from "@/components/ui/nav";
import {Toaster} from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = cookies();
    const theme = cookieStore.get('theme');

    return (
        <html lang="ja">
        <body data-mode={theme?.value}
              className={`${inter.className} h-svh`}
        >
            <Toaster/>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                {children}
            </ThemeProvider>
        </body>
        </html>
    );
}
