import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider"
import Nav from "@/components/ui/nav/nav";
import React, {ReactNode} from "react";
// import {locales} from '@/config';

type Props = {
    children: ReactNode;
    params: {locale: string};
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function LocaleLayout({ children, params: {locale} }: Readonly<{
    children: React.ReactNode;
    params: {locale: string};
}>) {
    return (
        <html lang={locale}>
            <body className={`${inter.className} h-svh`}>
                <Toaster/>
                <Nav/>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
